"""Initial schema — users, projects, project_members, tasks, comments.

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-23

This migration is hand-written on purpose. Autogenerate produces the same
DDL, but as a wall of unadorned ``op.create_*`` calls that hides the two
choices this migration is really about:

1. The **composite foreign key** on ``tasks`` — ``(project_id, assignee_id) →
   project_members(project_id, user_id)`` — which is how the database
   enforces "an assignee must be a member of the project".
2. Native Postgres **ENUM** types (``task_status``, ``task_priority``,
   ``member_role``) — created here so they exist by the time the tables
   reference them, and dropped in downgrade in reverse order.

Every migration from #2 onwards will be autogenerated. This one gets to be
verbose because it is the one people will actually read.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# ── Enum types ───────────────────────────────────────────────────────────────
# One Python object per Postgres type, reused below so the CREATE TYPE / DROP
# TYPE happen exactly once. ``create_type=False`` disables the *implicit*
# CREATE TYPE that ``sa.Column(task_status, ...)`` would otherwise emit
# alongside ``CREATE TABLE`` — we call ``.create(bind, checkfirst=False)``
# explicitly in ``upgrade()`` instead.
#
# Why ``postgresql.ENUM`` and not the generic ``sa.Enum``: in current
# SQLAlchemy + Alembic, the generic ``sa.Enum`` emits a CREATE TYPE per
# table that uses it, even with ``create_type=False`` set — which produces
# ``type "task_status" already exists`` on the second reference. The
# dialect-specific ``postgresql.ENUM`` honours the flag as intended. This
# is the classic Alembic-with-enums gotcha; the phase-1 brief writes it up.

task_status = postgresql.ENUM(
    "todo",
    "in_progress",
    "in_review",
    "done",
    name="task_status",
    create_type=False,
)
task_priority = postgresql.ENUM(
    "low",
    "medium",
    "high",
    name="task_priority",
    create_type=False,
)
member_role = postgresql.ENUM(
    "admin",
    "member",
    name="member_role",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()

    # Create the enum types first, once. Every `sa.Column(task_status, ...)`
    # below is told not to try creating the type again.
    task_status.create(bind, checkfirst=False)
    task_priority.create(bind, checkfirst=False)
    member_role.create(bind, checkfirst=False)

    # ── users ────────────────────────────────────────────────────────────────
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        # Belt-and-suspenders for the model's @validates hook: if any writer
        # bypasses the ORM, the database still rejects a non-lowercase email.
        sa.CheckConstraint(
            "email = lower(email)", name=op.f("ck_users_email_lowercase")
        ),
    )

    # ── projects ─────────────────────────────────────────────────────────────
    op.create_table(
        "projects",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column("key", sa.String(length=10), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_by",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("key", name=op.f("uq_projects_key")),
        sa.CheckConstraint(
            "key = upper(key)", name=op.f("ck_projects_key_uppercase")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_projects_created_by_users"),
        ),
    )

    # ── project_members ──────────────────────────────────────────────────────
    # No surrogate id; the composite (project_id, user_id) *is* the PK, and
    # that's exactly what the tasks composite FK below points at.
    op.create_table(
        "project_members",
        sa.Column(
            "project_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column("role", member_role, nullable=False),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_members_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_project_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "project_id", "user_id", name=op.f("pk_project_members")
        ),
    )

    # ── tasks ────────────────────────────────────────────────────────────────
    # The whole point of the schema, and the reason this migration is
    # hand-written: the composite FK on (project_id, assignee_id).
    op.create_table(
        "tasks",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "project_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", task_status, nullable=False),
        sa.Column("priority", task_priority, nullable=False),
        sa.Column(
            "assignee_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=True,
        ),
        sa.Column(
            "created_by",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        # "WEB-14" — a task's per-project number is unique.
        sa.UniqueConstraint(
            "project_id", "number", name="uq_tasks_project_number"
        ),
        # Plain FK to the project the task lives in.
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_tasks_project_id_projects"),
            ondelete="CASCADE",
        ),
        # The one every reader should stop and read.
        #
        # ``(project_id, assignee_id) → project_members(project_id, user_id)``
        #
        # This says: whatever project this task is in, if it *has* an
        # assignee, that user must already be a member of that project. If
        # assignee_id is NULL the constraint is not checked (SQL MATCH SIMPLE
        # default), so unassigned tasks are fine.
        #
        # A plain ``assignee_id → users.id`` could not express this — it
        # would only say the assignee is some valid user, not that they are
        # a member of *this* project.
        sa.ForeignKeyConstraint(
            ["project_id", "assignee_id"],
            ["project_members.project_id", "project_members.user_id"],
            name="fk_tasks_assignee_is_project_member",
        ),
        # Author of the row. A plain FK — no membership check, because a
        # user who later leaves a project can still be recorded as the
        # creator.
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_tasks_created_by_users"),
        ),
    )

    # ── comments ─────────────────────────────────────────────────────────────
    op.create_table(
        "comments",
        sa.Column(
            "id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "task_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column(
            "author_id",
            sa.dialects.postgresql.UUID(as_uuid=True),
            nullable=False,
        ),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_comments")),
        # ON DELETE CASCADE — the "deleting a task deletes its comments"
        # invariant from PLAN.md §5.
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["tasks.id"],
            name=op.f("fk_comments_task_id_tasks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_comments_author_id_users"),
        ),
    )


def downgrade() -> None:
    # Reverse-dependency order for the tables …
    op.drop_table("comments")
    op.drop_table("tasks")
    op.drop_table("project_members")
    op.drop_table("projects")
    op.drop_table("users")

    # … and then the enum types they used. Postgres will refuse to drop a
    # type while any table still references it, so this order matters.
    bind = op.get_bind()
    member_role.drop(bind, checkfirst=False)
    task_priority.drop(bind, checkfirst=False)
    task_status.drop(bind, checkfirst=False)
